spring.application.name=HibernateTest

spring.datasource.url = jdbc:postgresql://localhost:5432/palestra
spring.datasource.username=postgres
spring.datasource.password=postgres



spring.jpa.show.sql=true
spring.jpa.hibernate.ddl-auto=create
